# -----------------------------
# BUILD THE CURRENT SITE
# -----------------------------
remote_theme: "mmistakes/minimal-mistakes"   # later: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
title       : "Mohan Sai Teja Dantam"
description : "Ph.D. Student · LFCS · University of Edinburgh"
show_downloads: false        # Slate option → hides auto GitHub buttons

# -----------------------------
# GLOBAL SITE INFO (theme-agnostic)
# -----------------------------
url      : "https://mohanst.github.io"
baseurl  : ""                # root of the domain
lang     : "en-GB"

atom_feed:
  hide: true

# A few plugins already allowed by GitHub Pages and reused by MM
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author block (ignored by Slate, picked up automatically by Minimal-Mistakes)
author:
  name             : "Mohan sai teja Dantam"
  # avatar           : "/assets/images/me_0.jpg"
  bio              : ""
  location         : "Edinburgh"
  # email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mohan.dantam@ed.ac.uk"
      target: "_blank"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mohanst"
      target: "_blank"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=3KMIELcAAAAJ"
      target: "_blank"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohan-sai-teja-dantam/"
      target: "_blank"
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/cv/cv.pdf"
      target: "_blank"

# Optional analytics placeholder (works in both themes)
google_analytics: ""

# Navigation data kept separate so you can enable it later
# (Slate will simply ignore it.)
collections: []     # keeps GitHub-Pages “safe mode” happy

include:
- .htaccess
- _pages